2019-06-29 22:15:54,974 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:16:23,476 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:16:25,188 - flask.app - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/reubinoff/development/bills/bills_service/bills_service/routes/users.py", line 7, in get
    logging.info("Running in {} mode".format(app.config.get("MODE")))
NameError: name 'logging' is not defined
2019-06-29 22:16:35,345 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:16:37,369 - flask.app - ERROR - Exception on /users [GET]
Traceback (most recent call last):
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/reubinoff/development/bills/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/reubinoff/development/bills/bills_service/bills_service/routes/users.py", line 7, in get
    logging.info("Running in {} mode".format(app.config.get("MODE")))
NameError: name 'app' is not defined
2019-06-29 22:16:52,500 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:16:53,615 - root - INFO - Running in w mode
2019-06-29 22:16:55,892 - root - INFO - Running in w mode
2019-06-29 22:16:56,612 - root - INFO - Running in w mode
2019-06-29 22:16:56,875 - root - INFO - Running in w mode
2019-06-29 22:16:57,057 - root - INFO - Running in w mode
2019-06-29 22:17:54,114 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:20:20,674 - root - INFO - Running in DEVELOPMENT mode
2019-06-29 22:21:13,851 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:22:17,241 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:22:36,533 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:22:45,377 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:22:55,456 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:23:08,124 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:25:26,860 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:25:40,879 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:29:19,264 - root - INFO >> Running in DEVELOPMENT mode
2019-06-29 22:30:19,160 - root - INFO >> Running in DEVELOPMENT mode
